---
title: "ground_truth data calculation"
author: "Jiaxuan Li"
format: html
editor: visual
---

# Calculate DHS

## Set functions

```{r}
library(haven)
library(tidyverse)
library(here)

process_internet_use <- function(file_names, gender) {
  # Initialize an empty list to store data frames
  list_of_dataframes_int <- list()
  
  # Define selected variables based on gender
  selected_vars <- if(gender == "male") {
    c("v000", "v005","v012", "v171a") %>% 
      sapply(function(x) ifelse(startsWith(x, "v"), paste0("m", x), x)) %>% 
      unlist()
  } else {
    c("v000", "v005", "v012", "v171a")
  }
  
  # Determine the variable name for internet use based on gender
  internet_use_var <- if(gender == "male") "mv171a" else "v171a"
  age_var <- if(gender == "male") "mv012" else "v012"
  
  # Loop over each file name
  for (file in file_names) {
    # Read in the data from the DTA file with selected variables
    data <- read_dta(file, col_select = selected_vars) %>%
      mutate(harm = ifelse(max(!!sym(age_var)) < 50,0,1)) %>%
      group_by(!!sym(selected_vars[1])) %>%
      mutate(original_row = n()) %>%
      ungroup() %>%
      filter(!!sym(age_var) < 50)
    
    # Process the data for internet use based on the gender-specific variable
    processed_data_int <- data %>%
      mutate(Int_use_in_12 = case_when(
        !!sym(internet_use_var) == 1 ~ 1,
        is.na(!!sym(internet_use_var)) ~NA,
        T ~ 0),
             Int_use_before_12 = case_when(
               !!sym(internet_use_var) == 2 ~ 1,
               is.na(!!sym(internet_use_var)) ~NA,
               T ~ 0),
             Int_use_forget = case_when(
               !!sym(internet_use_var) == 3 ~ 1, 
               is.na(!!sym(internet_use_var)) ~NA,
               T ~ 0)) %>%
      filter(is.na(!!sym(internet_use_var)) == F) %>%
      group_by(!!sym(selected_vars[1])) %>%
      summarise(Int_use_in_12 = weighted.mean(Int_use_in_12, !!sym(selected_vars[2]), na.rm = TRUE),
                Int_use_before_12 = weighted.mean(Int_use_before_12, !!sym(selected_vars[2]), na.rm = TRUE),
                Int_use_forget = weighted.mean(Int_use_forget, !!sym(selected_vars[2]), na.rm = TRUE),
                harm = mean(harm),
                original_sample_size = mean(original_row),
                harmonized_sample_size_int = n(),
                .groups = 'drop')
    
    # Store the processed data in the list with the file name as key
    list_of_dataframes_int[[file]] <- processed_data_int
    
  }
  
  # Combine all data frames into one
  combined_data_int <- bind_rows(list_of_dataframes_int)
  
  return(combined_data_int)
}

check_files_for_variable <- function(file_list, variable_name) {
  files_without_variable <- c()  # Initialize an empty vector to store file names
  
  # Check each file for the specified variable
  for (file in file_list) {
    data <- tryCatch({
      read_dta(file, n_max = 1000)  # Try to read the first 1000 rows of the file
    }, error = function(e) {
      NULL  # Return NULL if there's an error reading the file
    })
    
    # If data is successfully read, check for the variable
    if (!is.null(data)) {
      # Check if the variable doesn't exist or only contains NA values
      if (!variable_name %in% names(data) || all(is.na(data[[variable_name]]), na.rm = FALSE)) {
        files_without_variable <- c(files_without_variable, file)
      }
    }
  }
  
  return(files_without_variable)  # Return the vector of file names
}


process_mobile_use <- function(file_names, gender) {
  # Initialize an empty list to store data frames
  list_of_dataframes <- list()
  
  # Define selected variables based on gender
  selected_vars <- if(gender == "male") {
    c("v000", "v005","v012", "v169a") %>% 
      sapply(function(x) ifelse(startsWith(x, "v"), paste0("m", x), x)) %>% 
      unlist()
  } else {
    c("v000", "v005","v012", "v169a")
  }
  
  # Determine the variable name for internet use based on gender
  mobile_use_var <- if(gender == "male") "mv169a" else "v169a"
  age_var <- if(gender == "male") "mv012" else "v012"
  # Loop over each file name
  for (file in file_names) {
    # Read in the data from the DTA file with selected variables
    data <- read_dta(file, col_select = selected_vars) %>%
      mutate(harm = ifelse(max(!!sym(age_var))< 50, 0, 1)) %>%
      group_by(!!sym(selected_vars[1])) %>%
      mutate(original_row = n()) %>%
      ungroup() %>%
      filter(!!sym(age_var) < 50)
    
    # Process the data for internet use based on the gender-specific variable
    processed_data <- data %>%
      filter(is.na(!!sym(mobile_use_var)) == F) %>%
      group_by(!!sym(selected_vars[1])) %>%
      summarise(mobile = weighted.mean(!!sym(mobile_use_var), !!sym(selected_vars[2]), na.rm = TRUE),
                harm = mean(harm),
                original_sample_size = mean(original_row),
                harmonized_sample_size_mobile = n(),
                .groups = 'drop') # Drop grouping for summarised df
    
    # Store the processed data in the list with the file name as key
    list_of_dataframes[[file]] <- processed_data
  }
  
  # Combine all data frames into one
  combined_data <- bind_rows(list_of_dataframes)
  
  return(combined_data)
}
```

## Calculate Int

```{r}
fefile_list_w7 <- list.files(here("data/national/data_refresh/dhs/wave7"), pattern = "IR", recursive = T, full.names = T)

fefile_list_w7_without_int <- check_files_for_variable(fefile_list_w7, "v171a")
fefile_list_w7 <- fefile_list_w7[!fefile_list_w7 %in% fefile_list_w7_without_int]
fefile_list_w7 <- fefile_list_w7[-c(22,25)]

fe_dhs_w7_int <- process_internet_use(fefile_list_w7, "female") %>%
  mutate(gender = "female",
         survey = "dhs7",
         country = c("Angola", "Armenia", "Benin", "Burundi", "Cameroon", "Ethiopia", "Gabon", "Guinea", "Haiti", "India", "Indonesia", "Jordan", "Liberia","Malawi","Maldives", "Mali","Mauritania","Nepal", "Nigeria", "Pakistan", "Papua New Guinea", "Sierra Leone","South Africa","Tanzania", "Timor-Leste","Uganda",  "Zambia", "Zimbabwe"),
         survey_start = c(2015, 2015, 2017, 2016, 2018, 2016, 2019, 2018, 2016, 2019, 2017, 2017, 2019, 2015, 2016, 2018, 2019, 2016, 2018, 2017, 2016, 2019, 2016, 2015, 2016, 2016, 2018, 2015),
         survey_duration = c(2,2,2,2,1,1,3,1,2,3,1,2,2,2,2, 1,3,1,1,2,3,1,1,2,1,1,1,1))

mfile_list_w7 <- list.files(here("data/national/data_refresh/dhs/wave7"), pattern = "MR7", recursive = T, full.names = T)
mfile_list_w7_without_int <- check_files_for_variable(mfile_list_w7, "mv171a")
mfile_list_w7 <- mfile_list_w7[!mfile_list_w7 %in% mfile_list_w7_without_int]
m_dhs_w7_int <- process_internet_use(mfile_list_w7, "male") %>%
  mutate(gender = "male",
         survey = "dhs7",
         country = c("Angola", "Armenia", "Benin", "Burundi", "Cameroon", "Ethiopia", "Gabon", "Guinea", "Haiti", "India", "Indonesia", "Jordan", "Liberia","Malawi","Maldives", "Mali","Mauritania","Nepal", "Nigeria", "Pakistan", "Papua New Guinea", "Sierra Leone","South Africa","Tanzania", "Timor-Leste","Uganda",  "Zambia", "Zimbabwe"),
         survey_start = c(2015, 2015, 2017, 2016, 2018, 2016, 2019, 2018, 2016, 2019, 2017, 2017, 2019, 2015, 2016, 2018, 2019, 2016, 2018, 2017, 2016, 2019, 2016, 2015, 2016, 2016, 2018, 2015),
         survey_duration = c(2,2,2,2,1,1,3,1,2,3,1,2,2,2,2, 1,3,1,1,2,3,1,1,2,1,1,1,1))

fefile_list_w8 <- list.files(here("data/national/data_refresh/dhs/wave8"), pattern = "IR", recursive = T, full.names = T)

fefile_list_w8 <- fefile_list_w8[-9]
fe_dhs_w8_int <- process_internet_use(fefile_list_w8, "female") %>%
  mutate(country = c("Burkina Faso","Cambodia", "Cote d'Ivoire","Gambia", "Ghana","Kenya",  "Madagascar", "Nepal", "Rwanda", "Tanzania"),
         survey_start = c(2021, 2021, 2021, 2019, 2022, 2022, 2021, 2022, 2019, 2022),
         survey_duration = c(1,2,1,2,1,1,1,1,2,1),
         gender = "female",
         survey = "dhs8")

mfile_list_w8 <- list.files(here("data/national/data_refresh/dhs/wave8"), pattern = "MR8", recursive = T, full.names = T)

m_dhs_w8_int <- process_internet_use(mfile_list_w8, "male") %>%
  mutate(country = c("Burkina Faso","Cambodia", "Cote d'Ivoire","Gambia", "Ghana","Kenya",  "Madagascar", "Nepal", "Rwanda", "Tanzania"),
         survey_start = c(2021, 2021, 2021, 2019, 2022, 2022, 2021, 2022, 2019, 2022),
         survey_duration = c(1,2,1,2,1,1,1,1,2,1),
         gender = "male",
         survey = "dhs8")

fefile_list_c <- list.files(here("data/national/data_refresh/dhs/continuous"), pattern = "IR", recursive = T, full.names = T)

fefile_list_c_without_int <- check_files_for_variable(fefile_list_c, "v171a")
fefile_list_c <- fefile_list_c[!fefile_list_c %in% fefile_list_c_without_int]

fe_dhs_c_int <- process_internet_use(fefile_list_c, "female") %>%
  mutate(country = "Senegal",
         gender = "female",
         survey_start = c(2017,2018,2019),
         survey_duration = c(1,1,1),
         survey = c("continuous dhs7","continuous dhs8", "continuous dhs8"))

mfile_list_c <- list.files(here("data/national/data_refresh/dhs/continuous"), pattern = "MR", recursive = T, full.names = T)
mfile_list_c_without_int <- check_files_for_variable(mfile_list_c, "mv171a")
mfile_list_c <- mfile_list_c[!mfile_list_c %in% mfile_list_c_without_int]

m_dhs_c_int <- process_internet_use(mfile_list_c, "male") %>%
  mutate(country = "Senegal",
         gender = "male",
         survey_start = c(2017,2018,2019),
         survey_duration = c(1,1,1),
         survey = c("continuous dhs7","continuous dhs8", "continuous dhs8"))

internet_penetration_dhs <- bind_rows(fe_dhs_c_int,fe_dhs_w7_int,fe_dhs_w8_int,m_dhs_c_int,m_dhs_w7_int,m_dhs_w8_int) %>%
  mutate(v000 = ifelse(is.na(v000),mv000,v000)) %>%
  select(-mv000)

write_csv(internet_penetration_dhs, here("data/national/data_refresh/DHS/internet_penetration_dhs.csv"))
```

## Test some of the result

```{r}
setwd(here("data/national/data_refresh/dhs/wave7/cameroon_2018"))
ca_fe <- read_dta("CMIR71FL.DTA", col_select = c("v000", "v005","v012", "v171a")) %>%
  mutate(harm = ifelse(max(v012) < 50, 0, 1)) %>%
  filter(v012 < 50) %>%
  group_by(v000) %>%
  mutate(int = ifelse(v171a == 1, 1, 0)) %>%
  summarise(int = weighted.mean(int, v005, na.rm = T),
            harm = mean(harm))

setwd(here("data/national/data_refresh/dhs/wave8/madagascar_2021"))
ma_m <- read_dta("MDMR81FL.DTA", col_select = c("mv000", "mv005","mv012", "mv171a")) %>%
  mutate(harm = ifelse(max(mv012) < 50, 0, 1)) %>%
  filter(mv012 < 50) %>% 
  group_by(mv000) %>%
  mutate(int = ifelse(mv171a == 1, 1, 0)) %>%
  summarise(int = weighted.mean(int, mv005, na.rm = T),
            harm = mean(harm))

##Find some errors in testing. Bugs are solved now.
```

## Calculate Mob

```{r}
fefile_list_w7 <- list.files(here("data/national/data_refresh/dhs/wave7"), pattern = "IR", recursive = T, full.names = T)

fefile_list_w7_without_mob <- check_files_for_variable(fefile_list_w7, "v169a")
fefile_list_w7 <- fefile_list_w7[!fefile_list_w7 %in% fefile_list_w7_without_mob]
fefile_list_w7
fefile_list_w7 <- fefile_list_w7[-c(4,24,27)]

fe_dhs_w7_mob <- process_mobile_use(fefile_list_w7, "female") %>%
  mutate(gender = "female",
         survey = "dhs7",
         country = c("Albania", "Angola", "Armenia", "Benin", "Burundi", "Cameroon", "Ethiopia", "Gabon", "Guinea", "Haiti", "India", "Indonesia", "Jordan", "Liberia","Malawi","Maldives", "Mali","Mauritania","Nepal", "Nigeria", "Pakistan", "Papua New Guinea", "Sierra Leone","South Africa","Tanzania", "Timor-Leste","Uganda",  "Zambia", "Zimbabwe"),
         survey_start = c(2017, 2015, 2015, 2017, 2016, 2018, 2016, 2019, 2018, 2016, 2019, 2017, 2017, 2019, 2015, 2016, 2018, 2019, 2016, 2018, 2017, 2016, 2019, 2016, 2015, 2016, 2016, 2018, 2015),
         survey_duration = c(2,2,2,2,2,1,1,3,1,2,3,1,2,2,2,2, 1,3,1,1,2,3,1,1,2,1,1,1,1))


fefile_list_w8 <- list.files(here("data/national/data_refresh/dhs/wave8"), pattern = "IR", recursive = T, full.names = T)
fefile_list_w8_without_mob <- check_files_for_variable(fefile_list_w8, "v169a")
fefile_list_w8 <- fefile_list_w8[!fefile_list_w8 %in% fefile_list_w8_without_mob]
fefile_list_w8 <- fefile_list_w8[-9]
fe_dhs_w8_mob <- process_mobile_use(fefile_list_w8, "female") %>%
  mutate(country = c("Burkina Faso","Cambodia", "Cote d'Ivoire","Gambia", "Ghana","Kenya",  "Madagascar", "Nepal", "Rwanda", "Tanzania"),
         survey_start = c(2021, 2021, 2021, 2019, 2022, 2022, 2021, 2022, 2019, 2022),
         survey_duration = c(1,2,1,2,1,1,1,1,2,1),
         gender = "female",
         survey = "dhs8")

fefile_list_c <- list.files(here("data/national/data_refresh/dhs/continuous"), pattern = "IR", recursive = T, full.names = T)

fefile_list_c_without_mob <- check_files_for_variable(fefile_list_c, "v169a")
fefile_list_c <- fefile_list_c[!fefile_list_c %in% fefile_list_c_without_int]

fe_dhs_c_mob <- process_mobile_use(fefile_list_c, "female") %>%
  mutate(country = "Senegal",
         gender = "female",
         survey_start = c(2017,2018,2019),
         survey_duration = c(1,1,1),
         survey = c("continuous dhs7","continuous dhs8", "continuous dhs8"))

mfile_list_w7 <- list.files(here("data/national/data_refresh/dhs/wave7"), pattern = "MR7", recursive = T, full.names = T)

mfile_list_w7_without_mob <- check_files_for_variable(mfile_list_w7, "mv169a")
mfile_list_w7 <- mfile_list_w7[!mfile_list_w7 %in% mfile_list_w7_without_mob]


m_dhs_w7_mob <- process_mobile_use(mfile_list_w7, "male") %>%
  mutate(gender = "male",
         survey = "dhs7",
         country = c("Albania", "Angola", "Armenia", "Benin", "Burundi", "Cameroon", "Ethiopia", "Gabon", "Guinea", "Haiti", "India", "Indonesia", "Jordan", "Liberia","Malawi","Maldives", "Mali","Mauritania","Nepal", "Nigeria", "Pakistan", "Papua New Guinea", "Sierra Leone","South Africa","Tanzania", "Timor-Leste","Uganda",  "Zambia", "Zimbabwe"),
         survey_start = c(2017, 2015, 2015, 2017, 2016, 2018, 2016, 2019, 2018, 2016, 2019, 2017, 2017, 2019, 2015, 2016, 2018, 2019, 2016, 2018, 2017, 2016, 2019, 2016, 2015, 2016, 2016, 2018, 2015),
         survey_duration = c(2,2,2,2,2,1,1,3,1,2,3,1,2,2,2,2, 1,3,1,1,2,3,1,1,2,1,1,1,1))

mfile_list_w8 <- list.files(here("data/national/data_refresh/dhs/wave8"), pattern = "MR8", recursive = T, full.names = T)

m_dhs_w8_mob <- process_mobile_use(mfile_list_w8, "male") %>%
  mutate(country = c("Burkina Faso","Cambodia", "Cote d'Ivoire","Gambia", "Ghana","Kenya",  "Madagascar", "Nepal", "Rwanda", "Tanzania"),
         survey_start = c(2021, 2021, 2021, 2019, 2022, 2022, 2021, 2022, 2019, 2022),
         survey_duration = c(1,2,1,2,1,1,1,1,2,1),
         gender = "male",
         survey = "dhs8")

mfile_list_c <- list.files(here("data/national/data_refresh/dhs/continuous"), pattern = "MR", recursive = T, full.names = T)
mfile_list_c_without_mob <- check_files_for_variable(mfile_list_c, "mv169a")
mfile_list_c <- mfile_list_c[!mfile_list_c %in% mfile_list_c_without_mob]

m_dhs_c_mob <- process_mobile_use(mfile_list_c, "male") %>%
  mutate(country = "Senegal",
         gender = "male",
         survey_start = c(2017,2018,2019),
         survey_duration = c(1,1,1),
         survey = c("continuous dhs7","continuous dhs8", "continuous dhs8"))

mobile_ownership_dhs <- bind_rows(fe_dhs_c_mob,fe_dhs_w7_mob,fe_dhs_w8_mob,m_dhs_c_mob,m_dhs_w7_mob,m_dhs_w8_mob) %>%
  mutate(v000 = ifelse(is.na(v000),mv000,v000)) %>%
  select(-mv000)

write_csv(mobile_ownership_dhs, here("data/national/data_refresh/DHS/mobile_ownership_dhs.csv"))
```

## Test some of the result

```{r}
setwd(here("data/national/data_refresh/dhs/wave7/ethiopia_2016"))
et_m <- read_dta("ETMR71FL.DTA", col_select = c("mv000", "mv005","mv012", "mv169a")) %>%
  mutate(harm = ifelse(max(mv012) < 50, 0, 1)) %>%
  filter(mv012 < 50) %>% 
  group_by(mv000) %>%
  summarise(mob = weighted.mean(mv169a, mv005, na.rm = T),
            harm = mean(harm))

setwd(here("data/national/data_refresh/dhs/continuous/senegal_2018"))
sn_m <- read_dta("SNIR81FL.DTA", col_select = c("v000", "v005","v012", "v169a")) %>%
  mutate(harm = ifelse(max(v012) < 50, 0, 1)) %>%
  filter(v012 < 50) %>% 
  group_by(v000) %>%
  summarise(mob = weighted.mean(v169a, v005, na.rm = T),
            harm = mean(harm))

##Everything looks fine
```

# Calculate MICS

## Get dir

```{r}
list_dir <- list.dirs(here("data/national/data_refresh/mics"), recursive = F, full.names = T)

list_dir

dir_with_mn <- c()
dir_without_mn <- c()

for (dir in list_dir) {
  file_list <- list.files(dir, recursive = T, pattern = ".sav",full.names = F)
  if ("mn.sav" %in% basename(file_list)) {
    dir_with_mn <- c(dir_with_mn, dir) 
    } else{
    
    dir_without_mn <- c(dir_without_mn, dir)
    }
}

##remove ethnic minority of Balkan countries. Remove Thailand 2019, process this later. Remove Pakistan, incomplete.
list_dir <- dir_with_mn[-c(16,23,27,28,29,30,35)]

wm_list <- c()
for (dir in list_dir) {
  file <- list.files(dir, recursive = T, pattern = "wm.sav",full.names = T)
  wm_list <- c(wm_list, file)
}

m_list <- c()
for (dir in list_dir) {
  file <- list.files(dir, recursive = T, pattern = "mn.sav",full.names = T)
  m_list <- c(m_list, file)
}
```

## Set function

```{r}
check_files_for_variable <- function(file_list, variable_name) {
  files_without_variable <- c()  # Initialize an empty vector to store file names
  
  # Check each file for the specified variable
  for (file in file_list) {
    data <- read_sav(file,n_max = 1000)
    
    # If data is successfully read, check for the variable
    if (!is.null(data)) {
      # Check if the variable doesn't exist or only contains NA values
      if (!variable_name %in% names(data) || all(is.na(data[[variable_name]]))) {
        files_without_variable <- c(files_without_variable, file)
      }
    }
  }
  
  return(files_without_variable)  # Return the vector of file names
}


internet_use_mics <- function(file_names, gender) {
  # Initialize an empty list to store data frames
  list_of_dataframes_int <- list()
  
  # Define selected variables based on gender
  selected_vars <- if (gender == "male") {
    c("MMT6C","MMT6F", "MMT9","MMT10","MWB4","mnweight")
  } else{
    c("MT6C","MT6F", "MT9","MT10","WB4","wmweight")
  }
  age_vars <- if (gender == "male") "MWB4" else "WB4"
  
  # Loop over each file name
  for (file in file_names) {
    # Read in the data from the DTA file with selected variables
    data <- read_sav(file, col_select = selected_vars) %>%
      mutate(harm = ifelse(max(!!sym(age_vars),na.rm = T) < 50,0,1),
             sample_size = n()) %>%
      filter(!!sym(age_vars) < 50)
    
    processed_data_int <- data %>%
      mutate(Int_use = case_when(
        !!sym(selected_vars[1]) == 1 | !!sym(selected_vars[2]) == 1 | !!sym(selected_vars[3]) == 1 ~ 1,
        is.na(!!sym(selected_vars[1])) & is.na(!!sym(selected_vars[2])) & is.na(!!sym(selected_vars[3]))  ~ NA,
        T ~ 0
      ),
      Int_use_in_3 = case_when(
        !!sym(selected_vars[4]) %in% c(1:3) ~ 1,
        is.na(!!sym(selected_vars[1])) & is.na(!!sym(selected_vars[2])) & is.na(!!sym(selected_vars[3]))  ~ NA,
        T ~ 0
      )) %>%
      filter(is.na(Int_use) == F) %>%
      summarise(Int_use = weighted.mean(Int_use, !!sym(selected_vars[6]), na.rm = TRUE),
                Int_use_in_3 = weighted.mean(Int_use_in_3, !!sym(selected_vars[6]), na.rm = TRUE),
                harm = mean(harm, na.rm = T),
                original_sample_size = mean(sample_size),
                harmonized_sample_size_int = n())
    
    # Store the processed data in the list with the file name as key
    list_of_dataframes_int[[file]] <- processed_data_int
    
  }
  
  # Combine all data frames into one
  combined_data_int <- bind_rows(list_of_dataframes_int)
  
  return(combined_data_int)
}

process_mobile_use_mics <- function(file_names, gender) {
  # Initialize an empty list to store data frames
  list_of_dataframes <- list()
  
  # Define selected variables based on gender
  selected_vars <- if(gender == "male") {
    c("MMT11", "MWB4","mnweight") 
  } else {
    c("MT11", "WB4","wmweight")
  }
  
  # Determine the variable name for internet use based on gender
  mobile_use_var <- if(gender == "male") "MMT11" else "MT11"
  age_var <- if(gender == "male") "MWB4" else "WB4"
  # Loop over each file name
  for (file in file_names) {
    # Read in the data from the DTA file with selected variables
    data <- read_sav(file, col_select = selected_vars) %>%
      mutate(harm = ifelse(max(!!sym(age_var),na.rm = T)< 50, 0, 1),
             sample_size  = n()) %>%
      filter(!!sym(age_var) < 50)
    
    # Process the data for internet use based on the gender-specific variable
    processed_data <- data %>%
      mutate(mb_use = case_when(
        !!sym(mobile_use_var) == 1 ~ 1,
        is.na(!!sym(mobile_use_var)) ~ NA,
        T ~ 0
      )) %>%
      filter(is.na(mb_use) == F) %>%
      summarise(mobile = weighted.mean(mb_use, !!sym(selected_vars[3]), na.rm = TRUE),
                harm = mean(harm, na.rm = T),
                harmonized_sample_size_mobile = n(),
                original_sample_size = mean(sample_size)) # Drop grouping for summarised df
    
    # Store the processed data in the list with the file name as key
    list_of_dataframes[[file]] <- processed_data
  }
  
  # Combine all data frames into one
  combined_data <- bind_rows(list_of_dataframes)
  
  return(combined_data)
}
```

## Check Variables

```{r}
wm_without_MT6C <- check_files_for_variable(wm_list,"MT6C")
wm_without_MT6F <- check_files_for_variable(wm_list,"MT6F")
wm_without_MT9 <- check_files_for_variable(wm_list,"MT9")
wm_without_MT10 <- check_files_for_variable(wm_list, "MT10")
wm_without_MT11 <- check_files_for_variable(wm_list, "MT11")
wm_without_MT6C
wm_without_MT6F
wm_without_MT9
wm_without_MT10
wm_without_MT11

m_without_MT6C <- check_files_for_variable(m_list, "MMT6C")
m_without_MT6F <- check_files_for_variable(m_list, "MMT6F")
m_without_MT9 <- check_files_for_variable(m_list, "MMT9")
m_without_MT10 <- check_files_for_variable(m_list, "MMT10")
m_without_MT11 <- check_files_for_variable(m_list, "MMT11")

m_without_MT6C
m_without_MT6F
m_without_MT9
m_without_MT10
m_without_MT11

TL <- here("data/national/data_refresh/mics/Thailand MICS6 and Thailand Selected 17 Provinces MICS6 Datasets 2019/Thailand MICS6 Datasets/Thailand MICS6 SPSS Datasets/wm.sav")
check_files_for_variable(TL, "MT9")

##No required questions for all surveys in Thailand

wm_list <- wm_list[!wm_list %in% wm_without_MT9]
m_list <- m_list[!m_list %in% m_without_MT9]
```

## Calculate Internet use

```{r}
intuse_mics_female <- internet_use_mics(wm_list,"female") %>%
  rename(Int_use_female = Int_use, Int_use_in_3_female = Int_use_in_3, original_sample_size_female = original_sample_size,harmonized_sample_size_int_female = harmonized_sample_size_int)
intuse_mics_male <- internet_use_mics(m_list, "male") %>%
  rename(Int_use_male = Int_use, Int_use_in_3_male = Int_use_in_3,original_sample_size_male = original_sample_size,harmonized_sample_size_int_male = harmonized_sample_size_int)

int_use_mics <- intuse_mics_female %>%
  bind_cols(intuse_mics_male) %>%
  select(Int_use_female, Int_use_in_3_female, Int_use_male, Int_use_in_3_male, original_sample_size_male,original_sample_size_female, harmonized_sample_size_int_male, harmonized_sample_size_int_female) %>%
  mutate(country = c("Benin","Central African Republic","Chad","Comoros","Cuba","DRCongo","Eswatini","Fiji","Ghana","Guinea Bissau","Guyana","Kiribati","Lao PDR","Lesotho","Madagascar","Malawi","Mongolia","Nepal","Nigeria","Samoa","Sao Tome and Principe","Sierra Leone","Suriname","The Gambia","Togo","Tonga","Tunisia","Turks and Caicos Islands","Tuvalu","Viet Nam","Zimbabwe"),
         survey_type = "mics6",
         survey_start = c("2021","2018","2019","2022","2019","2017","2021","2021","2017","2018","2019","2020","2017","2018","2018","2019","2018","2019","2021","2019","2019","2017","2018","2018","2017","2019","2018","2019","2019","2020","2019"),
         survey_duration = c(2,2,1,1,1,2,2,1,2,2,2,1,1,1,1,2,1,1,1,2,1,1, 1,1,1,1,1,2,2,2,1))

write_csv(int_use_mics, here("data/national/data_refresh/mics/int_use_mics.csv"))
```

## Test the result

```{r}
intuse_cuba <- read_sav(here("data/national/data_refresh/mics/Cuba MICS6 Datasets/Cuba MICS6 SPSS Datasets/mn.sav"), col_select = c("MMT6C","MMT6F","MMT9","MMT10","mnweight")) %>%
  mutate(int_use = case_when(
    MMT6C == 1 | MMT6F == 1 | MMT9 == 1 ~ 1,
    MMT6C == NA | MMT6F == NA | MMT9 == NA ~ NA,
    T ~ 0
  ),
  int_use_3 = case_when(
    MMT10 == 1 | MMT10 == 2 | MMT10 == 3 ~ 1,
    MMT6C == NA | MMT6F == NA | MMT9 == NA ~ NA,
    T ~ 0
  )) %>%
  summarise(int_use = weighted.mean(int_use, mnweight, na.rm = T),
            int_use_3 = weighted.mean(int_use_3, mnweight, na.rm = T))
                          
```

## Calculate Mobile use

```{r}
mb_use_mics_female <- process_mobile_use_mics(wm_list,"female")
mb_use_mics_male <- process_mobile_use_mics(m_list,"male")

list <- data.frame(wm_list,m_list)

m_list

mb_use_mics_female <- mb_use_mics_female %>%
  rename(mobile_female = mobile, original_sample_size_female = original_sample_size, harmonized_sample_size_mobile_female = harmonized_sample_size_mobile)

mb_use_mics_male <- mb_use_mics_male %>%
  rename(mobile_male = mobile, original_sample_size_male = original_sample_size, harmonized_sample_size_mobile_male = harmonized_sample_size_mobile)

mb_use_mics <- mb_use_mics_female %>%
  bind_cols(mb_use_mics_male) %>%
  select(mobile_female,mobile_male, original_sample_size_male, original_sample_size_female, harmonized_sample_size_mobile_male, harmonized_sample_size_mobile_female) %>%
  mutate(country = c("Benin","Central African Republic","Chad","Comoros","Cuba","DRCongo","Eswatini","Fiji","Ghana","Guinea Bissau","Guyana","Kiribati","Lao PDR","Lesotho","Madagascar","Malawi","Mongolia","Nepal","Nigeria","Samoa","Sao Tome and Principe","Sierra Leone","Suriname","The Gambia","Togo","Tonga","Tunisia","Turks and Caicos Islands","Tuvalu","Viet Nam","Zimbabwe"),
         survey_type = "mics6",
         survey_start = c("2021","2018","2019","2022","2019","2017","2021","2021","2017","2018","2019","2020","2017","2018","2018","2019","2018","2019","2021","2019","2019","2017","2018","2018","2017","2019","2018","2019","2019","2020","2019"),
         survey_duration = c(2,2,1,1,1,2,2,1,2,2,2,1,1,1,1,2,1,1,1,2,1,1, 1,1,1,1,1,2,2,2,1))

write_csv(mb_use_mics, here("data/national/data_refresh/mics/mb_use_mics.csv"))
```

# ITU

```{r}
setwd(here("data/national/data_refresh/itu"))

mob_female <- read_csv("mobile_female.csv", col_select = c("Economy","Value","Year"))
mob_male <- read_csv("mobile_male.csv", col_select = c("Economy","Value","Year"))

mob_use_itu <- mob_female %>%
  full_join(mob_male, by = "Economy") %>%
  rename(mobile_use_female = Value.x, mobile_use_male = Value.y, year = Year.x, country = Economy) %>%
  select(-Year.y) %>%
  mutate(survey_type = "itu")

int_female <- read_csv("int_female.csv", col_select = c("Economy","Value","Year"))
int_male <- read_csv("int_male.csv", col_select = c("Economy","Value","Year"))

int_use_itu <- int_female %>%
  full_join(int_male, by = "Economy") %>%
  rename(int_use_female = Value.x, int_use_male = Value.y, year = Year.x, country = Economy) %>%
  select(-Year.y) %>%
  mutate(survey_type = "itu")

write_csv(int_use_itu, here("data/national/data_refresh/itu/int_use_itu.csv"))
write_csv(mob_use_itu, here("data/national/data_refresh/itu/mob_use_itu.csv"))
```

# GSMA

```{r warning=FALSE}
list_gsma <- list.files(here("data/national/data_refresh/gsma/wetransfer_gsma-consumer-survey-data-2017-2022_2023-11-08_1555"), pattern = ".sav",full.names = T)

select_vars <- c("S0","S1","S2","Q5a","weight")

mob_gsma_2022 <- read_sav(list_gsma[6], col_select = select_vars) %>%
  mutate(mob_use_gsma = case_when(
    Q5a == 1 ~ 1,
    Q5a == 2 ~ 0,
    T ~ NA
  )) %>%
  group_by(S0,S1) %>%
  mutate(original_sample_size = n()) %>%
  filter(is.na(Q5a) == F) %>%
  summarise(mob_use_gsma = weighted.mean(mob_use_gsma, weight, na.rm = T),
            original_sample_size_without_na = n(),
            original_sample_size = mean(original_sample_size)) %>%
  mutate(year = 2022)

##harmonization
mob_gsma_2022_harm <- read_sav(list_gsma[6], col_select = select_vars) %>%
  mutate(mob_use_gsma = case_when(
    Q5a == 1 ~ 1,
    Q5a == 2 ~ 0,
    T ~ NA
  )) %>%
  filter(S2 %in% c(1:4)) %>%
  group_by(S0,S1,S2) %>%
  summarise(mob_use_gsma = weighted.mean(mob_use_gsma, weight, na.rm = T),
            n = n()) %>%
  mutate(n = ifelse(S2 == 4, n/2, n))

rows_to_add <- which(mob_gsma_2022_harm$S2 == 1)
result_mob_gsma_2022_harm <- mob_gsma_2022_harm

for (row in rev(rows_to_add)) {
  # Create a new row with specified conditions
  new_row <- data.frame(S0 = mob_gsma_2022_harm[row, "S0"],
                        S1 = mob_gsma_2022_harm[row, "S1"], 
                        S2 = 0, 
                        mob_use_gsma = mob_gsma_2022_harm[row, "mob_use_gsma"],
                        n = mob_gsma_2022_harm[row, "n"] * 3 / 7)
  
  # Insert the new row into the result dataframe
  result_mob_gsma_2022_harm <- rbind(result_mob_gsma_2022_harm[1:(row-1), ], new_row, result_mob_gsma_2022_harm[row:nrow(result_mob_gsma_2022_harm), ])
}

##it will add a duplicated row to the first row, because [1:0,0] will return the first row again, which is unnecessary.Just drop it.
result_mob_gsma_2022_harm <- result_mob_gsma_2022_harm[-1,]

##check if it is all right
count <- result_mob_gsma_2022_harm %>%
  group_by(S0,S1) %>%
  count()

##all good

result_mob_gsma_2022_harm <- result_mob_gsma_2022_harm %>%
  group_by(S0,S1) %>%
  summarise(mob_use_gsma_harm = weighted.mean(mob_use_gsma, n),
            harmonized_sample_size_mobile = sum(n))

mob_gsma_2022 <- full_join(mob_gsma_2022,result_mob_gsma_2022_harm, by = c("S1","S0"))

country_labels <- c("Bangladesh", "Egypt", "Ghana", "Guatemala", "India", "Indonesia", "Kenya", "Mexico", "Nigeria", "Pakistan", "Senegal", "Ethiopia")

labels <- setNames(country_labels, c(25, 32, 33, 34, 35, 36, 38, 39, 43, 44, 52, 56))

mob_gsma_2022$S0 <- factor(mob_gsma_2022$S0, levels = c(25, 32, 33, 34, 35, 36, 38, 39, 43, 44, 52, 56), labels = labels)

mob_gsma_2022$S1 <- factor(mob_gsma_2022$S1, levels = c(1,2), labels = c("male", "female"))

##let's test if this is right
mob_ba_2022 <- read_sav(list_gsma[6], col_select = select_vars) %>%
  filter(S0 == 25, S1 == 1) %>%
  mutate(mob_use_gsma = case_when(
    Q5a == 1 ~ 1,
    Q5a == 2 ~ 0,
    T ~ NA)) %>%
  filter(!is.na(mob_use_gsma)) %>%
  mutate(weighted_mob_use_gsma = mob_use_gsma*weight*474/sum(weight))

mob_use <- mean(mob_ba_2022$weighted_mob_use_gsma)
##seems right


select_vars <- c("S0","S1","S2","Q2a","Weight")
mob_gsma_2017 <- read_sav(list_gsma[1], col_select = select_vars) %>%
  mutate(mob_use_gsma = case_when(
    Q2a == 1 ~ 1,
    Q2a == 2 ~ 0,
    T ~ NA
  )) %>%
  group_by(S0,S1) %>%
  mutate(original_sample_size = n()) %>%
  filter(is.na(Q2a) == F) %>%
  summarise(mob_use_gsma = weighted.mean(mob_use_gsma, Weight, na.rm = T),
            original_sample_size_without_na = n(),
            original_sample_size = mean(original_sample_size)) %>%
  mutate(year = 2017)

##harmonize
mob_gsma_2017_harm <- read_sav(list_gsma[1], col_select = select_vars) %>%
  mutate(mob_use_gsma = case_when(
    Q2a == 1 ~ 1,
    Q2a == 2 ~ 0,
    T ~ NA
  )) %>%
  filter(S2 %in% c(1:4)) %>%
  group_by(S0,S1,S2) %>%
  summarise(mob_use_gsma = weighted.mean(mob_use_gsma, Weight, na.rm = T),
            n = n()) %>%
  mutate(n = ifelse(S2 == 4, n/2, n))

rows_to_add <- which(mob_gsma_2017_harm$S2 == 1)
result_mob_gsma_2017_harm <- mob_gsma_2017_harm

for (row in rev(rows_to_add)) {
  # Create a new row with specified conditions
  new_row <- data.frame(S0 = mob_gsma_2017_harm[row, "S0"],
                        S1 = mob_gsma_2017_harm[row, "S1"], 
                        S2 = 0, 
                        mob_use_gsma = mob_gsma_2017_harm[row, "mob_use_gsma"],
                        n = mob_gsma_2017_harm[row, "n"] * 3 / 7)
  
  # Insert the new row into the result dataframe
  result_mob_gsma_2017_harm <- rbind(result_mob_gsma_2017_harm[1:(row-1), ], new_row, result_mob_gsma_2017_harm[row:nrow(result_mob_gsma_2017_harm), ])
}

##it will add a duplicated row to the first row, because [1:0,0] will return the first row again, which is unnecessary.Just drop it.
result_mob_gsma_2017_harm <- result_mob_gsma_2017_harm[-1,]

##check if it is all right
count <- result_mob_gsma_2017_harm %>%
  group_by(S0,S1) %>%
  count()

##all good

result_mob_gsma_2017_harm <- result_mob_gsma_2017_harm %>%
  group_by(S0,S1) %>%
  summarise(mob_use_gsma_harm = weighted.mean(mob_use_gsma, n),
            harmonized_sample_size_mobile = sum(n))

mob_gsma_2017 <- full_join(mob_gsma_2017,result_mob_gsma_2017_harm, by = c("S1","S0"))

labels <- setNames(
  c("Australia", "Austria", "Belgium", "Canada", "Denmark", "Finland",
    "France", "Germany", "Great Britain", "Israel", "Italy", "Japan",
    "Netherlands", "Poland", "Qatar", "Russia", "Saudi Arabia (KSA)", "South Korea",
    "Spain", "Sweden", "Switzerland", "USA", "Algeria", "Argentina",
    "Bangladesh", "Brazil", "Cameroon", "Chile", "China", "Colombia",
    "Dominican Republic", "Egypt", "Ghana", "Guatemala", "India", "Indonesia",
    "Ivory Coast", "Kenya", "Mexico", "Morocco", "Myanmar", "Nicaragua",
    "Nigeria", "Pakistan", "Philippines", "Sierra Leone", "South Africa",
    "Tanzania", "Thailand", "Vietnam"),
  1:50)

mob_gsma_2017$S0 <- factor(mob_gsma_2017$S0, levels = 1:50, labels = labels)


mob_gsma_2017$S1 <- factor(mob_gsma_2017$S1, levels = c(1,2), labels = c("male", "female"))


select_vars <- c("S0","S1","S2","Q5a","weight")

mob_gsma_2018 <- read_sav(list_gsma[2], col_select = select_vars) %>%
  mutate(mob_use_gsma = case_when(
    Q5a == 1 ~ 1,
    Q5a == 2 ~ 0,
    T ~ NA
  )) %>%
  group_by(S0,S1) %>%
  mutate(original_sample_size = n()) %>%
  filter(is.na(Q5a) == F) %>%
  summarise(mob_use_gsma = weighted.mean(mob_use_gsma, weight, na.rm = T),
            original_sample_size_without_na = n(),
            original_sample_size = mean(original_sample_size)) %>%
  mutate(year = 2018)

mob_gsma_2018_harm <- read_sav(list_gsma[2], col_select = select_vars) %>%
  mutate(mob_use_gsma = case_when(
    Q5a == 1 ~ 1,
    Q5a == 2 ~ 0,
    T ~ NA
  )) %>%
  filter(S2 %in% c(1:4)) %>%
  group_by(S0,S1,S2) %>%
  summarise(mob_use_gsma = weighted.mean(mob_use_gsma, weight, na.rm = T),
            n = n()) %>%
  mutate(n = ifelse(S2 == 4, n/2, n))

rows_to_add <- which(mob_gsma_2018_harm$S2 == 1)
result_mob_gsma_2018_harm <- mob_gsma_2018_harm

for (row in rev(rows_to_add)) {
  # Create a new row with specified conditions
  new_row <- data.frame(S0 = mob_gsma_2018_harm[row, "S0"],
                        S1 = mob_gsma_2018_harm[row, "S1"], 
                        S2 = 0, 
                        mob_use_gsma = mob_gsma_2018_harm[row, "mob_use_gsma"],
                        n = mob_gsma_2018_harm[row, "n"] * 3 / 7)
  
  # Insert the new row into the result dataframe
  result_mob_gsma_2018_harm <- rbind(result_mob_gsma_2018_harm[1:(row-1), ], new_row, result_mob_gsma_2018_harm[row:nrow(result_mob_gsma_2018_harm), ])
}

##it will add a duplicated row to the first row, because [1:0,0] will return the first row again, which is unnecessary.Just drop it.
result_mob_gsma_2018_harm <- result_mob_gsma_2018_harm[-1,]

##check if it is all right
count <- result_mob_gsma_2018_harm %>%
  group_by(S0,S1) %>%
  count()

##all good

result_mob_gsma_2018_harm <- result_mob_gsma_2018_harm %>%
  group_by(S0,S1) %>%
  summarise(mob_use_gsma_harm = weighted.mean(mob_use_gsma, n),
            harmonized_sample_size_mobile = sum(n))

mob_gsma_2018 <- full_join(mob_gsma_2018,result_mob_gsma_2018_harm, by = c("S1","S0"))

labels <- setNames(
  c("Algeria", "Argentina", "Bangladesh", "Brazil", "China", "Dominican Republic", 
    "Guatemala", "India", "Indonesia", "Ivory Coast", "Kenya", "Mexico", "Myanmar", 
    "Nigeria", "Pakistan", "South Africa", "Tanzania", "Mozambique"),
  c(23, 24, 25, 26, 29, 31, 34, 35, 36, 37, 38, 39, 41, 43, 44, 47, 48, 51)
)

mob_gsma_2018$S0 <- factor(mob_gsma_2018$S0, levels = c(23, 24, 25, 26, 29, 31, 34, 35, 36, 37, 38, 39, 41, 43, 44, 47, 48, 51), labels = labels)

mob_gsma_2018$S1 <- factor(mob_gsma_2018$S1, levels = c(1,2), labels = c("male", "female"))


select_vars <- c("S0","S1","S2","Q5a","WEIGHT")

mob_gsma_2019 <- read_sav(list_gsma[3], col_select = select_vars) %>%
  mutate(mob_use_gsma = case_when(
    Q5a == 1 ~ 1,
    Q5a == 2 ~ 0,
    T ~ NA
  )) %>%
  group_by(S0,S1) %>%
  mutate(original_sample_size = n()) %>%
  filter(is.na(Q5a) == F) %>%
  summarise(mob_use_gsma = weighted.mean(mob_use_gsma, WEIGHT, na.rm = T),
            original_sample_size_without_na = n(),
            original_sample_size = mean(original_sample_size)) %>%
  mutate(year = 2019) %>%
  filter(S1 == 1 | S1 == 2)

mob_gsma_2019_harm <- read_sav(list_gsma[3], col_select = select_vars) %>%
  mutate(mob_use_gsma = case_when(
    Q5a == 1 ~ 1,
    Q5a == 2 ~ 0,
    T ~ NA
  )) %>%
  filter(S2 %in% c(1:4)) %>%
  group_by(S0,S1,S2) %>%
  summarise(mob_use_gsma = weighted.mean(mob_use_gsma, WEIGHT, na.rm = T),
            n = n()) %>%
  mutate(n = ifelse(S2 == 4, n/2, n)) %>%
  filter(S1 == 1 | S1 == 2)

rows_to_add <- which(mob_gsma_2019_harm$S2 == 1)
result_mob_gsma_2019_harm <- mob_gsma_2019_harm

for (row in rev(rows_to_add)) {
  # Create a new row with specified conditions
  new_row <- data.frame(S0 = mob_gsma_2019_harm[row, "S0"],
                        S1 = mob_gsma_2019_harm[row, "S1"], 
                        S2 = 0, 
                        mob_use_gsma = mob_gsma_2019_harm[row, "mob_use_gsma"],
                        n = mob_gsma_2019_harm[row, "n"] * 3 / 7)
  
  # Insert the new row into the result dataframe
  result_mob_gsma_2019_harm <- rbind(result_mob_gsma_2019_harm[1:(row-1), ], new_row, result_mob_gsma_2019_harm[row:nrow(result_mob_gsma_2019_harm), ])
}

##it will add a duplicated row to the first row, because [1:0,0] will return the first row again, which is unnecessary.Just drop it.
result_mob_gsma_2019_harm <- result_mob_gsma_2019_harm[-1,]

##check if it is all right
count <- result_mob_gsma_2019_harm %>%
  group_by(S0,S1) %>%
  count()

##all good, remember we only want male and female

result_mob_gsma_2019_harm <- result_mob_gsma_2019_harm %>%
  group_by(S0,S1) %>%
  summarise(mob_use_gsma_harm = weighted.mean(mob_use_gsma, n),
            harmonized_sample_size_mobile = sum(n))

mob_gsma_2019 <- full_join(mob_gsma_2019,result_mob_gsma_2019_harm, by = c("S1","S0"))

labels <- setNames(
  c("Australia", "Canada", "France", "Germany", "Great Britain", "Israel", "Italy", "Japan", 
    "Netherlands", "Poland", "Russia", "Saudi Arabia (KSA)", "South Korea", "Spain", "Sweden", 
    "USA", "Algeria", "Argentina", "Bangladesh", "Brazil", "Chile", "China", "Dominican Republic", 
    "Guatemala", "India", "Indonesia", "Kenya", "Mexico", "Myanmar", "Nigeria", "Pakistan", 
    "South Africa", "Mozambique", "Senegal", "Uganda", "Turkey"),
  c(1, 4, 7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 22, 23, 24, 25, 26, 28, 29, 31, 34, 35, 36, 38, 39, 41, 43, 44, 47, 51, 52, 53, 54)
)


mob_gsma_2019$S0 <- factor(mob_gsma_2019$S0, levels = c(1, 4, 7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 22, 23, 24, 25, 26, 28, 29, 31, 34, 35, 36, 38, 39, 41, 43, 44, 47, 51, 52, 53, 54), labels = labels)


mob_gsma_2019$S1 <- factor(mob_gsma_2019$S1, levels = c(1,2), labels = c("male", "female"))



select_vars <- c("S0","S1","S2","Q5a","WEIGHT")

mob_gsma_2020 <- read_sav(list_gsma[4], col_select = select_vars) %>%
  mutate(mob_use_gsma = case_when(
    Q5a == 1 ~ 1,
    Q5a == 2 ~ 0,
    T ~ NA
  )) %>%
  group_by(S0,S1) %>%
  mutate(original_sample_size = n()) %>%
  filter(is.na(Q5a) == F) %>%
  summarise(mob_use_gsma = weighted.mean(mob_use_gsma, WEIGHT, na.rm = T),
            original_sample_size_without_na = n(),
            original_sample_size = mean(original_sample_size)) %>%
  mutate(year = 2020)

mob_gsma_2020_harm <- read_sav(list_gsma[4], col_select = select_vars) %>%
  mutate(mob_use_gsma = case_when(
    Q5a == 1 ~ 1,
    Q5a == 2 ~ 0,
    T ~ NA
  )) %>%
  filter(S2 %in% c(1:4)) %>%
  group_by(S0,S1,S2) %>%
  summarise(mob_use_gsma = weighted.mean(mob_use_gsma, WEIGHT, na.rm = T),
            n = n()) %>%
  mutate(n = ifelse(S2 == 4, n/2, n))

rows_to_add <- which(mob_gsma_2020_harm$S2 == 1)
result_mob_gsma_2020_harm <- mob_gsma_2020_harm

for (row in rev(rows_to_add)) {
  # Create a new row with specified conditions
  new_row <- data.frame(S0 = mob_gsma_2020_harm[row, "S0"],
                        S1 = mob_gsma_2020_harm[row, "S1"], 
                        S2 = 0, 
                        mob_use_gsma = mob_gsma_2020_harm[row, "mob_use_gsma"],
                        n = mob_gsma_2020_harm[row, "n"] * 3 / 7)
  
  # Insert the new row into the result dataframe
  result_mob_gsma_2020_harm <- rbind(result_mob_gsma_2020_harm[1:(row-1), ], new_row, result_mob_gsma_2020_harm[row:nrow(result_mob_gsma_2020_harm), ])
}

##it will add a duplicated row to the first row, because [1:0,0] will return the first row again, which is unnecessary.Just drop it.
result_mob_gsma_2020_harm <- result_mob_gsma_2020_harm[-1,]

##check if it is all right
count <- result_mob_gsma_2020_harm %>%
  group_by(S0,S1) %>%
  count()

##all good

result_mob_gsma_2020_harm <- result_mob_gsma_2020_harm %>%
  group_by(S0,S1) %>%
  summarise(mob_use_gsma_harm = weighted.mean(mob_use_gsma, n),
            harmonized_sample_size_mobile = sum(n))

mob_gsma_2020 <- full_join(mob_gsma_2020,result_mob_gsma_2020_harm, by = c("S1","S0"))

labels <- setNames(
  c("Algeria", "Bangladesh", "Guatemala", "India", "Kenya", "Nigeria", "Pakistan", "Mozambique"),
  c(23, 25, 34, 35, 38, 43, 44, 51)
)

mob_gsma_2020$S0 <- factor(mob_gsma_2020$S0, levels = c(23, 25, 34, 35, 38, 43, 44, 51), labels = labels)

mob_gsma_2020$S1 <- factor(mob_gsma_2020$S1, levels = c(1,2), labels = c("male", "female"))


select_vars <- c("S0","S1","S2","Q5a","WEIGHT")

mob_gsma_2021 <- read_sav(list_gsma[5], col_select = select_vars) %>%
  mutate(mob_use_gsma = case_when(
    Q5a == 1 ~ 1,
    Q5a == 2 ~ 0,
    T ~ NA
  )) %>%
  group_by(S0,S1) %>%
  mutate(original_sample_size = n()) %>%
  filter(is.na(Q5a) == F) %>%
  summarise(mob_use_gsma = weighted.mean(mob_use_gsma, WEIGHT, na.rm = T),
            original_sample_size_without_na = n(),
            original_sample_size = mean(original_sample_size)) %>%
  mutate(year = 2021)

mob_gsma_2021_harm <- read_sav(list_gsma[5], col_select = select_vars) %>%
  mutate(mob_use_gsma = case_when(
    Q5a == 1 ~ 1,
    Q5a == 2 ~ 0,
    T ~ NA
  )) %>%
  filter(S2 %in% c(1:4)) %>%
  group_by(S0,S1,S2) %>%
  summarise(mob_use_gsma = weighted.mean(mob_use_gsma, WEIGHT, na.rm = T),
            n = n()) %>%
  mutate(n = ifelse(S2 == 4, n/2, n))

rows_to_add <- which(mob_gsma_2021_harm$S2 == 1)
result_mob_gsma_2021_harm <- mob_gsma_2021_harm

for (row in rev(rows_to_add)) {
  # Create a new row with specified conditions
  new_row <- data.frame(S0 = mob_gsma_2021_harm[row, "S0"],
                        S1 = mob_gsma_2021_harm[row, "S1"], 
                        S2 = 0, 
                        mob_use_gsma = mob_gsma_2021_harm[row, "mob_use_gsma"],
                        n = mob_gsma_2021_harm[row, "n"] * 3 / 7)
  
  # Insert the new row into the result dataframe
  result_mob_gsma_2021_harm <- rbind(result_mob_gsma_2021_harm[1:(row-1), ], new_row, result_mob_gsma_2021_harm[row:nrow(result_mob_gsma_2021_harm), ])
}

##it will add a duplicated row to the first row, because [1:0,0] will return the first row again, which is unnecessary.Just drop it.
result_mob_gsma_2021_harm <- result_mob_gsma_2021_harm[-1,]

##check if it is all right
count <- result_mob_gsma_2021_harm %>%
  group_by(S0,S1) %>%
  count()

##all good

result_mob_gsma_2021_harm <- result_mob_gsma_2021_harm %>%
  group_by(S0,S1) %>%
  summarise(mob_use_gsma_harm = weighted.mean(mob_use_gsma, n),
            harmonized_sample_size_mobile = sum(n))

mob_gsma_2021 <- full_join(mob_gsma_2021,result_mob_gsma_2021_harm, by = c("S1","S0"))

country_names <- c("Bangladesh", "Egypt", "Guatemala", "India", "Indonesia", "Kenya", "Mexico", "Nigeria", "Pakistan", "Senegal")

labels <- setNames(country_names, c(25, 32, 34, 35, 36, 38, 39, 43, 44, 52))

mob_gsma_2021$S0 <- factor(mob_gsma_2021$S0, levels = c(25, 32, 34, 35, 36, 38, 39, 43, 44, 52), labels = labels)

mob_gsma_2021$S1 <- factor(mob_gsma_2021$S1, levels = c(1,2), labels = c("male", "female"))

mob_gsma_male <- bind_rows(mob_gsma_2017,mob_gsma_2018,mob_gsma_2019,mob_gsma_2020,mob_gsma_2021,mob_gsma_2022) %>%
  filter(S1 == "male") %>%
  rename(mob_use_gsma_male = mob_use_gsma, mob_use_gsma_harm_male = mob_use_gsma_harm, original_sample_size_without_na_male = original_sample_size_without_na, original_sample_size_male = original_sample_size, harmonized_sample_size_mobile_male = harmonized_sample_size_mobile)

mob_gsma_female <- bind_rows(mob_gsma_2017,mob_gsma_2018,mob_gsma_2019,mob_gsma_2020,mob_gsma_2021,mob_gsma_2022) %>%
  filter(S1 == "female") %>%
  rename(mob_use_gsma_female = mob_use_gsma, mob_use_gsma_harm_female = mob_use_gsma_harm, original_sample_size_without_na_female = original_sample_size_without_na, original_sample_size_female = original_sample_size, harmonized_sample_size_mobile_female = harmonized_sample_size_mobile)

mob_gsma <- mob_gsma_male %>%
  full_join(mob_gsma_female, by = c("S0","year")) 

mob_gsma <- mob_gsma %>%
  select(-S1.x, -S1.y) %>%
  rename(country = S0)

write_csv(mob_gsma, here("data/national/data_refresh/gsma/mob_gsma.csv"))
```

# Try to combine data

```{r}
list <- list.files(here("data/national/data_refresh"), pattern = ".csv",full.names = T,recursive = T)
list
list <- list[-c(3,5,6,9,10,13:22)]
list

int_dhs <- read_csv(list[1])

int_dhs <- int_dhs %>%
  mutate(int_use = Int_use_in_12 + Int_use_before_12 +Int_use_forget,
         int_use_in_12 = Int_use_in_12) %>%
  select(-c(v000,harm,Int_use_in_12:Int_use_forget))

int_dhs_female <- int_dhs %>%
  filter(gender == "female") %>%
  rename(n_wom = original_sample_size,
         n_age_15_to_49_wom_valid_internet = harmonized_sample_size_int,
         perc_ever_used_internet_wght_age_15_to_49_wom = int_use,
         perc_used_internet_past12months_wght_age_15_to_49_wom = int_use_in_12) %>%
  select(-gender)

int_dhs_male <- int_dhs %>%
  filter(gender == "male") %>%
  rename(n_men = original_sample_size,
         n_age_15_to_49_men_valid_internet = harmonized_sample_size_int,
         perc_ever_used_internet_wght_age_15_to_49_men = int_use,
         perc_used_internet_past12months_wght_age_15_to_49_men = int_use_in_12) %>%
  select(-gender)

int_dhs_wide <- int_dhs_male %>%
  full_join(int_dhs_female) %>%
  rename(survey_type = survey)


int_mics <- read_csv(list[6])

int_mics <- int_mics %>%
  rename(perc_ever_used_internet_wght_age_15_to_49_wom = Int_use_female,
         perc_ever_used_internet_wght_age_15_to_49_men = Int_use_male,
         perc_used_internet_past3months_wght_age_15_to_49_wom = Int_use_in_3_female, 
         perc_used_internet_past3months_wght_age_15_to_49_men = Int_use_in_3_male,
         n_wom = original_sample_size_female,
         n_men = original_sample_size_male,
         n_age_15_to_49_wom_valid_internet = harmonized_sample_size_int_female,
         n_age_15_to_49_men_valid_internet = harmonized_sample_size_int_male)

int_use <- bind_rows(int_dhs_wide, int_mics)

int_itu <- read_csv(list[4])

int_itu <- int_itu %>%
  mutate(perc_used_internet_past3months_wom = as.numeric(sub("%", "", int_use_female)) / 100,
         perc_used_internet_past3months_men = as.numeric(sub("%","", int_use_male)) / 100) %>%
  rename(survey_start = year) %>%
  select(-int_use_female, -int_use_male)

int_use <- bind_rows(int_use, int_itu)


mob_dhs <- read_csv(list[2])

mob_dhs_male <- mob_dhs %>%
  filter(gender == "male") %>%
  select(-v000, -gender, -harm) %>%
  rename(perc_owns_mobile_telephone_wght_age_15_to_49_men = mobile, n_men = original_sample_size, n_age_15_to_49_men_valid_mobile = harmonized_sample_size_mobile)
  

mob_dhs_female <- mob_dhs %>%
  filter(gender == "female") %>%
  select(-v000, -gender, -harm) %>%
  rename(perc_owns_mobile_telephone_wght_age_15_to_49_wom = mobile, n_wom = original_sample_size, n_age_15_to_49_wom_valid_mobile = harmonized_sample_size_mobile)

mob_dhs_wide <- mob_dhs_male %>%
  full_join(mob_dhs_female) %>%
  rename(survey_type = survey)

mob_mics <- read_csv(list[7])

mob_mics <- mob_mics %>%
  rename(perc_owns_mobile_telephone_wght_age_15_to_49_men = mobile_male,
         perc_owns_mobile_telephone_wght_age_15_to_49_wom = mobile_female,
         n_men = original_sample_size_male,
         n_wom = original_sample_size_female,
         n_age_15_to_49_men_valid_mobile = harmonized_sample_size_mobile_male,
         n_age_15_to_49_wom_valid_mobile = harmonized_sample_size_mobile_female)

mobile_ownership <- bind_rows(mob_dhs_wide, mob_mics)

mob_gsma <- read_csv(list[3])

mob_gsma <- mob_gsma %>%
  rename(perc_owns_mobile_telephone_wght_men = mob_use_gsma_male, 
         perc_owns_mobile_telephone_wght_wom = mob_use_gsma_female,
         perc_owns_mobile_telephone_wght_age_15_to_49_men = mob_use_gsma_harm_male, 
         perc_owns_mobile_telephone_wght_age_15_to_49_wom = mob_use_gsma_harm_female, 
         n_men = original_sample_size_male,
         n_wom = original_sample_size_female,
         n_age_15_to_49_men_valid_mobile = harmonized_sample_size_mobile_male,
         n_age_15_to_49_wom_valid_mobile = harmonized_sample_size_mobile_female,
         n_men_valid_mobile = original_sample_size_without_na_male,
         n_wom_valid_mobile = original_sample_size_without_na_female,
         survey_start = year) %>%
  mutate(survey_type = "gsma")

mobile_ownership <- bind_rows(mobile_ownership, mob_gsma)


mob_itu <- read_csv(list[5])

mob_itu <- mob_itu %>%
  mutate(perc_owns_mobile_telephone_wght_wom = as.numeric(sub("%", "", mobile_use_female)) / 100,
         perc_owns_mobile_telephone_wght_men = as.numeric(sub("%","", mobile_use_male)) / 100) %>%
  rename(survey_start = year) %>%
  select(-c("mobile_use_female","mobile_use_male"))

mobile_ownership <- bind_rows(mobile_ownership, mob_itu)

full_groundtruth <- int_use %>%
  full_join(mobile_ownership)


```

# Population data

```{r}
##population data
library(janitor)
library(readxl)

data_female <- read_excel(here("data/national/data_refresh/population_data/WPP2022_POP_F01_3_POPULATION_SINGLE_AGE_FEMALE.xlsx"))

data_female <- data_female[-c(1:11),]

data_female <- data_female %>%
  row_to_names(row_number = 1)

data_female <- data_female %>%
  filter(Type == "Country/Area", Year > 2001) %>%
  mutate(survey_start = as.numeric(Year))

data_female[, 12:112] <- lapply(data_female[, 12:112], function(x) as.numeric(as.character(x)))

data_female$pop_female <- rowSums(data_female[, 12:112], na.rm = TRUE)
data_female$pop_15_to_49_female <- rowSums(data_female[, 27:61], na.rm = T)

pop_female <- data_female %>%
  select(`Region, subregion, country or area *`,
         survey_start,
         pop_female,
         pop_15_to_49_female) %>%
  rename(country = `Region, subregion, country or area *`)

data_male <- read_excel(here("data/national/data_refresh/population_data/WPP2022_POP_F01_2_POPULATION_SINGLE_AGE_MALE.xlsx"))

data_male <- data_male[-c(1:11),]

data_male <- data_male %>%
  row_to_names(row_number = 1)

data_male <- data_male %>%
  filter(Type == "Country/Area", Year > 2001) %>%
  mutate(survey_start = as.numeric(Year))

data_male[, 12:112] <- lapply(data_male[, 12:112], function(x) as.numeric(as.character(x)))

data_male$pop_male <- rowSums(data_male[, 12:112], na.rm = TRUE)
data_male$pop_15_to_49_male <- rowSums(data_male[, 27:61], na.rm = T)

pop_male <- data_male %>%
  select(`Region, subregion, country or area *`,
         survey_start,
         pop_male,
         pop_15_to_49_male) %>%
  rename(country = `Region, subregion, country or area *`)

pop <- full_join(pop_female, pop_male)

pop_2022 <- pop %>%
  filter(survey_start == 2021) %>%
  mutate(survey_start = 2022)

pop <- bind_rows(pop,pop_2022)

full_groundtruth <- full_groundtruth %>%
  mutate(country = case_when(
    country == "Tanzania" ~ "United Republic of Tanzania",
    country == "Cote d'Ivoire" ~ "Côte d'Ivoire",
    country == "DRCongo" ~ "Democratic Republic of the Congo",
    country == "Guinea Bissau" ~ "Guinea-Bissau",
    country == "Lao PDR" ~ "Lao People's Democratic Republic",
    country == "The Gambia" ~ "Gambia",
    country == "Curacao" ~ "Curaçao",
    country == "Czech Republic" ~ "Czechia",
    country == "Dominican Rep." ~ "Dominican Republic",
    country == "Hong Kong, China" ~ "China, Hong Kong SAR",
    country == "Korea (Rep. of)" ~ "Republic of Korea",
    country == "Kosovo" ~ "Kosovo (under UNSC res. 1244)",
    country == "Macao, China" ~ "China, Macao SAR",
    country == "Taiwan, Province of China" ~ "China, Taiwan Province of China",
    country %in% c("United States", "USA") ~ "United States of America",
    country == "Great Britain" ~ "United Kingdom",
    country == "Russia" ~ "Russian Federation",
    country == "Saudi Arabia (KSA)" ~ "Saudi Arabia",
    country == "South Korea" ~ "Dem. People's Republic of Korea",
    country == "Ivory Coast" ~ "Côte d'Ivoire",
    country == "Vietnam" ~ "Viet Nam",
    country == "Turkey" ~ "Türkiye",
    country == "Venezuela" ~ "Venezuela (Bolivarian Republic of)",
    T ~ country
  ))

full_groundtruth_pop <- full_groundtruth %>%
  left_join(pop, by = c("country","survey_start")) 
rows_with_na_pop <- full_groundtruth_pop[is.na(full_groundtruth_pop$pop_female), ]

```

# Calculate number of user

```{r}
full_groundtruth_pop <- read_csv(here("data/national/data_refresh/full_groundtruth.csv"))

full_groundtruth_pop <- full_groundtruth_pop %>%
  mutate(n_ever_used_internet_age_15_to_49_men = perc_ever_used_internet_wght_age_15_to_49_men * pop_15_to_49_male,
         n_ever_used_internet_age_15_to_49_wom = perc_ever_used_internet_wght_age_15_to_49_wom * pop_15_to_49_female,
         n_used_internet_past12months_age_15_to_49_men = perc_used_internet_past12months_wght_age_15_to_49_men * pop_15_to_49_male,
         n_used_internet_past12months_age_15_to_49_wom = perc_used_internet_past12months_wght_age_15_to_49_wom * pop_15_to_49_female,
         n_used_internet_past3months_age_15_to_49_men = ifelse(is.na(perc_used_internet_past3months_wght_age_15_to_49_men) == T, perc_used_internet_past3months_men, perc_used_internet_past3months_wght_age_15_to_49_men) * pop_15_to_49_male,
         n_used_internet_past3months_age_15_to_49_wom = ifelse(is.na(perc_used_internet_past3months_wght_age_15_to_49_wom) == T, perc_used_internet_past3months_wom, perc_used_internet_past3months_wght_age_15_to_49_wom) * pop_15_to_49_female,
         n_owns_mobile_telephone_age_15_to_49_men = ifelse(is.na(perc_owns_mobile_telephone_wght_age_15_to_49_men) == T, perc_owns_mobile_telephone_wght_men, perc_owns_mobile_telephone_wght_age_15_to_49_men) * pop_15_to_49_male,
         n_owns_mobile_telephone_age_15_to_49_wom = ifelse(is.na(perc_owns_mobile_telephone_wght_age_15_to_49_wom) == T, perc_owns_mobile_telephone_wght_wom, perc_owns_mobile_telephone_wght_age_15_to_49_wom) * pop_15_to_49_female,
         ) %>%
  mutate(perc_ever_used_internet_wght_fm_count_ratio =  n_ever_used_internet_age_15_to_49_wom/n_ever_used_internet_age_15_to_49_men,
         perc_ever_used_internet_wght_fm_perc_ratio =  perc_ever_used_internet_wght_age_15_to_49_wom/perc_ever_used_internet_wght_age_15_to_49_men,
         perc_used_internet_past12months_wght_fm_count_ratio = n_used_internet_past12months_age_15_to_49_wom/n_used_internet_past12months_age_15_to_49_men,
         perc_used_internet_past12months_wght_fm_perc_ratio = perc_used_internet_past12months_wght_age_15_to_49_wom/perc_used_internet_past12months_wght_age_15_to_49_men,
         perc_used_internet_past3months_wght_fm_count_ratio = n_used_internet_past3months_age_15_to_49_wom/n_used_internet_past3months_age_15_to_49_men,
         perc_used_internet_past3months_wght_fm_perc_ratio = ifelse(is.na(perc_used_internet_past3months_wght_age_15_to_49_wom) == T, perc_used_internet_past3months_wom, perc_used_internet_past3months_wght_age_15_to_49_wom)/ifelse(is.na(perc_used_internet_past3months_wght_age_15_to_49_men) == T, perc_used_internet_past3months_men, perc_used_internet_past3months_wght_age_15_to_49_men),
         perc_owns_mobile_telephone_wght_fm_count_ratio = n_owns_mobile_telephone_age_15_to_49_wom/n_owns_mobile_telephone_age_15_to_49_men,
         perc_owns_mobile_telephone_wght_fm_perc_ratio = ifelse(is.na(perc_owns_mobile_telephone_wght_age_15_to_49_wom) == T, perc_owns_mobile_telephone_wght_wom, perc_owns_mobile_telephone_wght_age_15_to_49_wom)/ifelse(is.na(perc_owns_mobile_telephone_wght_age_15_to_49_men) == T, perc_owns_mobile_telephone_wght_men, perc_owns_mobile_telephone_wght_age_15_to_49_men),
         survey_end = survey_start + survey_duration - 1)

write_csv(full_groundtruth_pop, here("data/national/data_refresh/full_groundtruth.csv"))


```
